type BilingualCopy = readonly [en: string, zhCn: string];

export interface CountryContextQuestionCopy {
  prompt: BilingualCopy;
  explain: BilingualCopy;
}

/**
 * Individually authored replacements for the old landscape/signature templates.
 *
 * Each row contains:
 * country | landscape prompt EN | landscape prompt ZH | landscape explanation EN |
 * landscape explanation ZH | culture prompt EN | culture prompt ZH |
 * culture explanation EN | culture explanation ZH
 */
const RAW_COUNTRY_CONTEXT_COPY = `
Algeria|Tassili n'Ajjer rises from which broader landscape that dominates southern Algeria?|塔西利山脉从哪片主导阿尔及利亚南部的广阔地貌中升起？|Tassili n'Ajjer's sandstone plateaus and rock art sites stand within the Sahara, where wind has sculpted dunes and stone.|塔西利山脉的砂岩高原与岩画遗址位于撒哈拉之中，风在这里共同塑造沙丘与岩石。|Which musical tradition grew around Oran before gaining listeners far beyond Algeria?|哪种音乐传统兴起于奥兰，后来走出阿尔及利亚、传向更广阔的世界？|Raï developed in western Algeria; tea hospitality remains another familiar part of journeys through the desert regions.|拉伊音乐兴起于阿尔及利亚西部；在沙漠地区，以茶待客也是旅行者常见的生活传统。
Argentina|A journey east from Patagonia's ice fields would cross which characteristic southern landscape?|从巴塔哥尼亚冰原向东旅行，最可能穿越哪种典型的南部景观？|Patagonia links Andean glaciers in the west with broad, windswept grasslands stretching toward the Atlantic.|巴塔哥尼亚西部有安第斯冰川，向东则展开一直延伸至大西洋的多风草原。|Which dance emerged around the Río de la Plata and became an international symbol of Argentina?|哪种舞蹈兴起于拉普拉塔河地区，后来成为阿根廷广为人知的文化象征？|Tango took shape in the port neighbourhoods of Buenos Aires and Montevideo before spreading around the world.|探戈形成于布宜诺斯艾利斯和蒙得维的亚的港口街区，随后传播到世界各地。
Australia|A traveller approaching Uluru is entering which vast Australian region?|旅行者接近乌鲁鲁时，正在进入澳大利亚哪种广阔区域？|Uluru rises from the arid Red Centre, part of the immense inland country commonly called the Outback.|乌鲁鲁耸立在干旱的“红色中心”，这里属于常被称为内陆荒原的广大区域。|Which pairing reflects species and vegetation that evolved during Australia's long geographic isolation?|哪一组合体现了澳大利亚长期地理隔离中演化出的动物与植被？|Kangaroos are native marsupials, while eucalyptus woodland shapes habitats across much of the continent.|袋鼠是澳大利亚原生有袋类，桉树林则构成大陆许多地区的重要生境。
Brazil|Which landscape stores an immense share of Brazil's freshwater and biodiversity?|哪种景观汇集了巴西极其丰富的淡水与生物多样性？|The Amazon basin contains the world's largest tropical rainforest and a vast network of rivers and wetlands.|亚马孙流域拥有世界最大的热带雨林，以及庞大的河流与湿地网络。|Which music-and-parade tradition is central to the famous celebrations before Lent in Rio de Janeiro?|里约热内卢在大斋期前举行的著名庆典，以哪种音乐和巡游传统为核心？|Samba schools prepare music, dance and elaborate floats for Rio's Carnival parades.|桑巴学校会为里约狂欢节准备音乐、舞蹈和大型花车巡游。
Canada|A route through Banff and Jasper is most closely associated with which scenery?|穿越班夫和贾斯珀的旅程，最容易遇到哪种景观？|The Canadian Rockies combine glacier-fed lakes with mountain forests that merge into the country's broad boreal zone.|加拿大落基山脉分布着冰川补给的湖泊与山地森林，并与广阔北方森林带相连。|Which emblem became the centrepiece of Canada's national flag in 1965?|1965年启用的加拿大国旗以什么图案作为中央标志？|The stylised maple leaf has long associations with Canada and became the flag's central symbol in 1965.|枫叶长期与加拿大联系在一起，并在1965年成为国旗的中央图案。
Chile|Which journey best captures Chile's extraordinary north-to-south environmental range?|哪段旅程最能体现智利从北到南巨大的环境差异？|Chile stretches from the hyper-arid Atacama through Mediterranean valleys to the ice fields and grasslands of Patagonia.|智利从极端干旱的阿塔卡马，经地中海气候谷地，一直延伸到巴塔哥尼亚冰原与草原。|Which two industries reflect both Chile's geology and its Mediterranean-climate central valleys?|哪两种产业分别体现了智利的矿产地质与中部地中海气候谷地？|Chile is a leading copper producer, while its central valleys support vineyards along the Pacific side of the Andes.|智利是重要铜生产国，中部谷地则在安第斯山太平洋一侧孕育了大片葡萄园。
China|Which structure follows ridges and passes across much of northern China rather than forming one unbroken wall?|哪项建筑沿中国北方的山脊与关隘延伸，而不是一条从未中断的单体城墙？|The Great Wall is a network of fortifications built and rebuilt in different periods across northern China.|长城是中国北方多个时期修建、重建的防御设施网络。|Which animal depends heavily on bamboo forests in the mountains of central China?|哪种动物高度依赖中国中部山地的竹林生境？|Giant pandas feed chiefly on bamboo and survive in fragmented mountain forests in central China.|大熊猫主要以竹子为食，现存栖息地集中在中国中部彼此分隔的山地森林。
Egypt|Why did ancient settlement and monumental building concentrate along a narrow strip through Egypt's deserts?|为什么古埃及的聚落与大型建筑集中在穿越沙漠的一条狭长地带？|The Nile supplied water, fertile floodplain soils and transport through an otherwise arid landscape.|尼罗河在干旱环境中提供水源、肥沃的泛滥平原土壤和交通通道。|Which system allowed temple and tomb walls to preserve names, offerings and royal events in ancient Egypt?|古埃及神庙和墓葬墙面依靠哪套系统记录姓名、祭品与王室事件？|Hieroglyphic writing combined sound signs and meaning signs across monuments, ritual objects and administrative texts.|象形文字把表音符号与表意符号结合起来，广泛用于纪念建筑、宗教器物和行政记录。
Ethiopia|Which geological process helped create Ethiopia's high plateaus and the deep trough of the East African Rift?|哪种地质过程共同塑造了埃塞俄比亚高原与东非大裂谷的深切谷地？|Uplift and rifting produced dramatic escarpments, volcanic terrain and isolated massifs such as the Simien Mountains.|地壳抬升与裂谷活动形成陡崖、火山地貌和塞米恩山脉等孤立山体。|In which tradition are beans roasted, ground and brewed for guests through a deliberately unhurried ceremony?|哪项传统会为客人现场烘焙、研磨并冲煮咖啡，整个过程刻意保持从容？|The Ethiopian coffee ceremony turns preparation and repeated servings into an important act of hospitality and community.|埃塞俄比亚咖啡仪式把制作过程与多轮分享变成重要的待客和社区活动。
France|Which southern French region is especially known for lavender fields beside hill towns and Mediterranean vegetation?|法国南部哪个地区尤其以薰衣草田、山城与地中海植被相伴而闻名？|Provence combines lavender-growing plateaus, historic villages and landscapes shaped by the Mediterranean climate.|普罗旺斯把种植薰衣草的高原、历史村镇与地中海气候景观结合在一起。|Which everyday social setting helped make bread, cheese and conversation part of France's international cultural image?|哪种日常社交空间，使面包、奶酪与交谈共同进入法国广为人知的文化形象？|Cafés, bakeries and local markets connect food traditions with daily public life in French towns and cities.|咖啡馆、面包店和地方市场把饮食传统与法国城镇的日常公共生活连接起来。
Germany|Along which river can travellers see vineyards and castles above a deeply cut valley?|旅行者沿哪条河流前行，可以看到葡萄园与城堡分布在深切河谷两侧？|The Rhine Gorge is known for steep vineyards, fortified hilltops and settlements shaped by a major European waterway.|莱茵河谷以陡坡葡萄园、山顶城堡和沿欧洲重要水道发展的聚落著称。|Which pairing links a winter civic tradition with Germany's long reputation for manufacturing?|哪一组合把德国的冬季城市传统与长期制造业声誉联系在一起？|Christmas markets animate town squares, while precision engineering has shaped German industry and exports.|圣诞市集让冬季城市广场充满活力，精密工程则长期影响德国工业与出口。
Greece|Why are many Cycladic villages built as clusters of white houses above the Aegean Sea?|为什么基克拉泽斯群岛的许多村镇以白色房屋成片分布在爱琴海上方？|Compact whitewashed settlements respond to intense sun, limited land and the steep terrain of Aegean islands.|紧凑的白色聚落适应了爱琴海岛屿强烈日照、有限土地与陡峭地形。|Which two inheritances connect ancient public performance with a crop cultivated around Greece for millennia?|哪两项遗产分别连接古代公共表演与希腊延续数千年的栽培作物？|Ancient theatres remain prominent archaeological sites, while olives have long shaped Greek farming, food and trade.|古代剧场至今仍是重要遗址，橄榄则长期影响希腊的农业、饮食与贸易。
India|Which river plain supported dense settlement and pilgrimage routes near many of northern India's historic cities?|哪片河流平原支撑了印度北部众多历史城市附近的密集聚落与朝圣路线？|The Ganges plain combines fertile alluvial soils with cities and sacred places linked by the river.|恒河平原拥有肥沃冲积土，沿河分布着相互联系的城市与宗教圣地。|Which festival is marked by rows of lamps, family gatherings and regional traditions across India?|印度哪个节日以成排灯火、家庭团聚和各地不同传统为鲜明特征？|Diwali is celebrated in varied ways across India, with lamps symbolising the victory of light over darkness.|排灯节在印度各地庆祝方式不尽相同，灯火通常象征光明战胜黑暗。
Indonesia|Why do volcanic slopes and rice terraces often appear in the same Indonesian landscape?|为什么火山坡地与水稻梯田经常共同出现在印度尼西亚景观中？|Volcanic soils can be fertile, while terraces and irrigation help farmers cultivate steep, rain-rich islands.|火山土壤往往肥沃，梯田与灌溉则帮助人们在多雨岛屿的陡坡上耕作。|Which textile method creates patterns by applying wax before successive dye baths?|哪种织物工艺会先涂蜡防染，再经过多轮染色形成图案？|Batik artisans use wax-resist dyeing to build layered patterns with strong regional identities across Indonesia.|蜡染工匠利用涂蜡防染逐层形成图案，在印度尼西亚各地发展出鲜明地域风格。
Iran|What design principle links water channels, shade and geometry in the traditional Persian garden?|传统波斯花园如何把水渠、阴凉与几何布局联系在一起？|Persian gardens organise water and planted spaces into ordered refuges set against Iran's often dry surroundings.|波斯花园以秩序化方式组织水体与植物空间，在伊朗常见的干旱环境中营造绿洲。|Which crafts turned knots, glazed tiles and repeating geometry into portable and architectural art?|哪些工艺分别把结结、釉面砖与重复几何图案发展成可携带和建筑性的艺术？|Carpet weaving and tilework are major Iranian arts, carrying regional designs into homes, mosques and palaces.|地毯编织和瓷砖装饰是伊朗重要艺术，把地域图案带入住宅、清真寺与宫殿。
Italy|Which central Italian landscape was shaped by hill towns, vineyards and centuries of intensive farming?|意大利中部哪种景观由山城、葡萄园和数百年的精细农业共同塑造？|Tuscany's celebrated scenery is a cultural landscape formed by agriculture, settlement and historic stone towns.|托斯卡纳著名风光是一种由农业、聚落和历史石城共同形成的文化景观。|Which pairing links Italy's city-state patronage with strong regional food identities?|哪一组合把意大利城邦赞助艺术的历史与鲜明地方饮食传统联系起来？|Renaissance art flourished in cities such as Florence, while pasta traditions developed many distinct regional forms.|文艺复兴艺术在佛罗伦萨等城市繁荣，意面传统也在各地区发展出不同形态。
Japan|Why does Mount Fuji appear repeatedly in pilgrimage accounts, woodblock prints and modern photography?|为什么富士山反复出现在朝圣记录、浮世绘和现代摄影中？|Its symmetrical volcanic profile is both a commanding landscape feature and a long-standing cultural and spiritual subject.|它对称的火山轮廓既是醒目的自然地标，也是延续已久的文化与精神主题。|Which contrast is a familiar part of travelling between major Japanese cities?|在日本主要城市之间旅行时，哪种对比最为典型？|High-speed Shinkansen trains connect modern cities where historic temples remain active parts of urban life.|高速新干线连接现代城市，而历史寺院仍是城市生活中的活跃组成部分。
Kazakhstan|How did open steppe shape movement and pastoral life across much of Kazakhstan?|辽阔草原如何影响哈萨克斯坦大部分地区的迁徙与畜牧生活？|The steppe favoured long-distance seasonal movement, while places such as Charyn reveal the region's contrasting canyon terrain.|草原适合长距离季节性迁徙，恰伦等地的峡谷则展现了这一地区另一种鲜明地貌。|Which skills and dwelling reflect traditions adapted to mobile life on the Central Asian steppe?|哪些技艺与居所体现了适应中亚草原流动生活的传统？|Eagle hunting and the portable ger both belong to pastoral traditions shared across parts of the Central Asian steppe.|猎鹰技艺与便于迁移的毡房，都属于中亚部分草原地区共享的牧业传统。
Mexico|Why do cenotes cluster across the limestone landscape of the Yucatán Peninsula?|为什么天然井密集分布在尤卡坦半岛的石灰岩地貌中？|Rainwater dissolves porous limestone and exposes underground water, creating features important to Maya settlement and belief.|雨水溶蚀多孔石灰岩并显露地下水，形成对玛雅聚落和信仰都很重要的天然井。|Which flower is commonly used to guide memory and decorate offerings during Día de Muertos?|亡灵节期间，人们常用哪种花寄托记忆并装饰祭坛？|Bright marigolds line altars and paths during Día de Muertos, a tradition centred on remembering the dead.|鲜艳的万寿菊常用于装饰亡灵节祭坛与道路，这一传统的核心是纪念逝者。
Mongolia|Why can Mongolia's landscape shift from grassland to the stony expanses of the Gobi?|为什么蒙古国的景观会从草原过渡到戈壁的石质荒原？|Its continental interior spans broad steppe and arid southern basins with large seasonal temperature extremes.|蒙古国地处大陆内部，既有辽阔草原，也有干旱的南部盆地，季节温差很大。|Which festival events preserve skills once essential to pastoral and mounted life?|哪个节日通过竞赛保存了曾对游牧和骑乘生活十分重要的技能？|Naadam centres on horse racing, wrestling and archery, while the ger remains a practical portable home.|那达慕以赛马、摔跤和射箭为核心，蒙古包则仍是适合迁徙的实用居所。
Morocco|A route from Marrakesh toward the Sahara must cross which major mountain barrier?|从马拉喀什前往撒哈拉的路线需要翻越哪座主要山地屏障？|The Atlas Mountains divide Atlantic and Mediterranean regions from valleys leading toward the Sahara.|阿特拉斯山脉把大西洋、地中海一侧与通往撒哈拉的谷地分隔开来。|Which decorative craft builds geometric surfaces from precisely cut glazed tiles?|哪种装饰工艺利用精确切割的釉面砖拼成几何图案？|Zellige tilework covers fountains, courtyards and religious buildings; mint tea accompanies Morocco's hospitality traditions.|泽利杰瓷砖装饰常见于喷泉、庭院与宗教建筑，薄荷茶则与摩洛哥待客传统相伴。
Netherlands|How did windmills contribute to creating and maintaining Dutch polders?|风车如何参与荷兰圩田的形成与维护？|Wind-powered pumps moved water out of low-lying land, complementing dikes and canals in a managed water system.|风力水泵把低地积水排出，与堤坝和运河共同构成受管理的水利系统。|Which two everyday sights reflect horticultural trade and people-centred urban transport in the Netherlands?|荷兰哪两种日常景象分别体现园艺贸易与以人为本的城市交通？|Tulip cultivation supports a major flower industry, while cycling is built into daily travel in many Dutch communities.|郁金香种植支撑重要花卉产业，自行车则融入许多荷兰社区的日常出行。
Norway|What does a traveller see where glacial valleys continue below sea level along Norway's coast?|当冰川谷地在挪威海岸延伸到海平面以下时，旅行者会看到什么景观？|Seawater fills the deep troughs to form fjords bordered by steep rock walls and high coastal mountains.|海水进入深切谷地，形成两侧为陡峭岩壁和高山的峡湾。|Which surviving buildings show how medieval Scandinavian carpenters adapted timber construction to Christian worship?|哪些保存至今的建筑说明中世纪斯堪的纳维亚木匠如何让木构技术服务基督教礼拜？|Norway's stave churches combine a Christian church plan with highly developed traditions of timber framing.|挪威木板教堂把基督教堂布局与成熟的木构架传统结合起来。
Pakistan|Which two physical systems have most strongly organised settlement in northern and central Pakistan?|哪两大自然系统最深刻地组织了巴基斯坦北部与中部的聚落分布？|The Karakoram contains some of Earth's highest peaks, while the Indus and its tributaries sustain broad agricultural plains.|喀喇昆仑拥有地球上一些最高峰，印度河及其支流则滋养着广阔农业平原。|Which moving canvases turn commercial vehicles into displays of regional craft and identity?|哪种“移动画布”把商用车辆变成展现地方工艺与身份的载体？|Pakistan's truck art covers vehicles with painted scenes, calligraphy, metalwork and brightly coloured ornament.|巴基斯坦卡车艺术以彩绘场景、书法、金属工艺和鲜艳装饰覆盖车辆。
Peru|Why could the Inca build a major estate high above the Urubamba valley?|为什么印加人能够在乌鲁班巴河谷上方的高山环境中建设大型遗址？|Terracing, stone engineering and careful water management adapted steep Andean slopes for settlement and cultivation.|梯田、石工与精细水利让陡峭安第斯山坡能够承载聚落与耕作。|Which pairing connects Andean fibre traditions with a dish shaped by Peru's Pacific coast?|哪一组合把安第斯纤维工艺与受秘鲁太平洋海岸影响的菜肴联系起来？|Andean communities maintain rich weaving traditions, while ceviche uses fresh seafood cured with citrus and seasoning.|安第斯社区延续丰富编织传统，酸橘汁腌鱼则以新鲜海产、柑橘汁和调味料制成。
Poland|Which trade once carried Baltic amber southward from the Polish coast into continental Europe?|哪种贸易曾把波兰海岸的波罗的海琥珀向南输送到欧洲大陆？|Baltic ports and overland amber routes linked the coast with inland markets for centuries.|数百年来，波罗的海港口与陆上琥珀路线把海岸和内陆市场连接起来。|Which food-and-craft pairing links a filled dumpling tradition with material gathered on the Baltic shore?|哪一组合把包馅面食传统与波罗的海岸采集的材料联系起来？|Pierogi appear in many regional forms, while Baltic amber has long supported jewellery and decorative crafts.|波兰饺子在各地有不同做法，波罗的海琥珀则长期用于珠宝和装饰工艺。
Portugal|Why do Atlantic-facing cliffs and tiled streets appear together in many images of Portugal?|为什么面向大西洋的海崖与铺满瓷砖的街巷经常共同出现在葡萄牙影像中？|Portugal's long Atlantic edge shaped maritime settlements, while azulejo tiles became a distinctive layer of urban architecture.|葡萄牙漫长的大西洋海岸塑造了海洋聚落，阿兹勒赫瓷砖则成为城市建筑的鲜明表层。|Which urban music is traditionally performed with expressive singing and Portuguese guitar?|哪种城市音乐传统以富有情感的歌唱和葡萄牙吉他演奏著称？|Fado developed especially in Lisbon and Coimbra, while azulejo tilework records religious, civic and everyday scenes.|法多尤其在里斯本与科英布拉发展，阿兹勒赫瓷砖则记录宗教、城市与日常场景。
Russia|What makes Lake Baikal stand out within the immense forest belt of Siberia?|贝加尔湖在西伯利亚广阔森林带中为何格外突出？|Baikal occupies an ancient rift basin and is the world's deepest lake, surrounded by taiga and mountain landscapes.|贝加尔湖位于古老裂谷盆地，是世界最深湖泊，周围分布针叶林与山地。|Which forms became widely recognised through Russian church architecture and folk craft?|哪些形象分别通过俄罗斯宗教建筑与民间工艺而广为人知？|Onion domes shape many church skylines, while nested matryoshka dolls became a popular form of painted folk craft.|洋葱穹顶塑造许多教堂天际线，套娃则成为广为流传的彩绘民间工艺。
Saudi Arabia|How can a journey in Saudi Arabia connect immense dune fields with coral-rich coastal water?|沙特阿拉伯的一段旅程如何把巨大沙丘与珊瑚丰富的海域连接起来？|The Arabian interior contains major sand seas, while the country's long western edge follows the Red Sea.|阿拉伯内陆分布着大型沙海，国家漫长的西部边界则沿红海展开。|Which serving ritual turns small cups of lightly roasted coffee into a sign of welcome?|哪种奉茶仪式把一小杯杯浅焙咖啡变成欢迎来客的象征？|Arabic coffee is commonly offered to guests in small cups, expressing generosity and desert hospitality.|阿拉伯咖啡常以小杯连续招待客人，表达慷慨与沙漠待客传统。
Singapore|How does Singapore combine dense urban development with equatorial vegetation?|新加坡如何把高密度城市建设与赤道植被结合起来？|Tropical gardens, street trees and restored habitats are woven through a compact skyline and major transport hub.|热带花园、行道树与修复生境穿插在紧凑的城市天际线和大型交通枢纽之间。|Which institutions bring Chinese, Malay, Indian and other food traditions together under one roof?|哪种场所把华人、马来人、印度人等多种饮食传统汇聚在同一屋檐下？|Hawker centres organise many affordable specialist stalls into shared social spaces central to everyday life.|小贩中心把众多价格亲民、各有所长的摊位组织成共享社交空间，是日常生活的重要部分。
South Africa|Which route can connect savanna wildlife, the Drakensberg escarpment and the stormy Cape coast?|哪段旅程能够把稀树草原野生动物、德拉肯斯堡陡崖与多风的开普海岸连接起来？|South Africa spans interior plateaus, dramatic mountain edges and coastlines influenced by two oceans.|南非横跨内陆高原、陡峭山缘，以及受两大洋影响的漫长海岸。|Which plant produces a caffeine-free infusion native to the Cederberg region?|哪种植物原产于塞德贝格地区，可制成天然不含咖啡因的饮品？|Rooibos grows naturally in South Africa's fynbos region, alongside a national identity strongly linked with diverse wildlife.|路易波士原生于南非凡波斯植被区，这个国家也以多样野生动物著称。
South Korea|Why do historic temples often appear on wooded slopes close to South Korea's dense cities?|为什么韩国的历史寺院经常坐落在距离高密度城市不远的林木山坡上？|Mountain terrain occupies much of the peninsula, allowing old religious landscapes and modern urban regions to exist side by side.|山地覆盖半岛大部分区域，使古老宗教景观与现代城市能够近距离并存。|Which food preserves vegetables through fermentation and appears in countless regional variations?|哪种食物通过发酵保存蔬菜，并发展出众多地方做法？|Kimchi is a diverse family of fermented foods, while contemporary Korean music and media have found global audiences.|泡菜是一大类多样的发酵食品；与此同时，韩国当代音乐与媒体也吸引了全球受众。
Spain|Which architectural legacy is especially visible in the courtyards, water channels and decoration of southern Spain?|西班牙南部的庭院、水渠与装饰中，哪段建筑遗产尤其清晰可见？|Centuries of Islamic rule left major monuments and design traditions across Andalusia beside the Mediterranean.|数百年伊斯兰统治在地中海沿岸的安达卢西亚留下重要建筑与设计传统。|Which performance tradition combines song, guitar, rhythmic handclaps and dance?|哪种表演传统把歌唱、吉他、节奏性拍手与舞蹈结合起来？|Flamenco developed from several cultural influences in Andalusia and is performed through music, voice and movement.|弗拉门戈在安达卢西亚多种文化影响中形成，通过音乐、歌声与身体动作共同呈现。
Switzerland|Why do glaciers and clear lakes frequently occupy the same Swiss Alpine journey?|为什么冰川与清澈湖泊经常出现在同一段瑞士阿尔卑斯旅程中？|Glaciers carve basins and valleys, while their meltwater feeds lakes and rivers descending from the high Alps.|冰川切割盆地与山谷，融水则补给从阿尔卑斯高处流下的湖泊与河流。|Which industries pair precision mechanics with a product shaped by imported cacao and Swiss processing?|哪两项产业把精密机械与一种依靠进口可可、在瑞士加工发展的产品联系起来？|Watchmaking grew in specialised Alpine and Jura workshops, while Swiss chocolatiers developed influential processing methods.|钟表制造在阿尔卑斯与汝拉山区的专业作坊中发展，瑞士巧克力制造者则改进了重要加工方法。
Thailand|What links southern Thailand's limestone towers with its island-fringed bays?|泰国南部的石灰岩塔峰为何会与岛屿密布的海湾共同出现？|Water dissolved and eroded ancient limestone, leaving karst cliffs, caves and islands along the tropical coast.|水长期溶蚀古老石灰岩，在热带海岸留下喀斯特峭壁、洞穴与岛屿。|During which celebration do public water splashing and visits to elders mark the traditional new year?|哪个节日期间，人们以泼水和拜访长辈迎接传统新年？|Songkran combines family and religious customs with public water festivities; street food remains central to daily urban life.|宋干节把家庭、宗教习俗与公共泼水活动结合起来，街头美食则是城市日常生活的重要部分。
Turkey|Which waterway makes Istanbul a meeting point between the Black Sea and the Mediterranean world?|哪条水道让伊斯坦布尔成为黑海与地中海世界之间的交汇点？|The Bosphorus divides the city's European and Asian sides and connects the Black Sea route toward the Mediterranean.|博斯普鲁斯海峡分隔城市的欧亚两侧，并把黑海航路连接到地中海方向。|Which public spaces historically combined long-distance trade with tea, textiles and specialised crafts?|哪些公共空间在历史上把远距离贸易与茶、纺织品及专业手工艺汇聚起来？|Covered bazaars organised merchants by trade, while carpets and tea remain visible parts of Turkish material and social culture.|有顶集市按行业组织商人，地毯与红茶至今仍是土耳其物质和社交文化中的常见元素。
United Arab Emirates|What contrast defines the approach to cities such as Dubai and Abu Dhabi?|接近迪拜和阿布扎比等城市时，哪种强烈对比最为醒目？|Dense high-rise skylines rise beside arid dunes and a shallow, intensely hot Gulf coast.|密集高楼天际线紧邻干旱沙丘，以及水浅而炎热的海湾海岸。|Which heritage practice trained birds of prey to help people obtain food in a harsh desert environment?|哪项传统曾训练猛禽，帮助人们在严酷沙漠环境中获取食物？|Falconry began as a practical hunting skill and remains an important heritage practice alongside traditional markets.|猎鹰最初是一项实用狩猎技能，如今与传统市集一样，仍是重要文化遗产。
United Kingdom|How can one journey connect chalk sea cliffs, green uplands and castles guarding old routes?|一段旅程如何把白垩海崖、绿色高地与守卫古老通道的城堡连接起来？|The United Kingdom's varied geology and long-settled landscape place dramatic coasts close to farmed hills and historic fortifications.|英国多样地质与长期有人居住的景观，使壮观海岸、农耕丘陵与历史防御建筑彼此相近。|Which London vehicle became a moving civic symbol alongside the social ritual of afternoon tea?|哪种伦敦交通工具与下午茶这一社交习惯一样，成为广为辨认的城市文化符号？|Red double-decker buses became icons of London, while afternoon tea developed as a distinct social custom.|红色双层巴士成为伦敦标志，下午茶则发展为一种独特社交习惯。
United States of America|Why can national-park journeys in the United States reveal canyons, glaciers, geysers and deserts?|为什么美国的国家公园旅程能够同时展现峡谷、冰川、间歇泉与沙漠？|The country spans a continent-scale range of climates and geology, preserved in an extensive national-park system.|美国横跨大陆尺度的气候与地质区域，并通过广泛的国家公园体系加以保护。|Which two twentieth-century industries transformed local performance and storytelling into global popular culture?|二十世纪哪两种产业把地方表演与叙事转化为影响全球的流行文化？|Jazz grew from African American musical traditions, while Hollywood developed into a major centre of film production.|爵士乐源于非裔美国人的音乐传统，好莱坞则发展成重要电影生产中心。
Vietnam|How did water shape both the limestone towers of Hạ Long Bay and the rice-growing lowlands of Vietnam?|水如何同时塑造下龙湾的石灰岩塔峰与越南种植水稻的低地？|Dissolution sculpted coastal karst, while rivers and monsoon rains support deltas and carefully managed rice terraces.|溶蚀作用塑造海岸喀斯特，河流与季风降雨则滋养三角洲和精细管理的稻田梯地。|Which performance tradition uses a flooded stage to animate stories of village life and legend?|哪种表演传统以水面为舞台，演绎乡村生活与传说故事？|Water puppetry developed in the northern delta, while phở reflects Vietnam's equally distinctive street-food culture.|水上木偶戏兴起于北部三角洲，越南粉则体现了同样鲜明的街头饮食文化。
`.trim();

export const COUNTRY_CONTEXT_QUESTION_COPY =
  parseCountryContextRows(RAW_COUNTRY_CONTEXT_COPY);

function parseCountryContextRows(
  raw: string,
): Readonly<Record<string, readonly [
  CountryContextQuestionCopy,
  CountryContextQuestionCopy,
]>> {
  const entries = raw.split("\n").map((line) => {
    const fields = line.split("|");
    if (fields.length !== 9) {
      throw new Error(
        `Country context row must have 9 fields, got ${fields.length}.`,
      );
    }
    const [
      country,
      landscapePromptEn,
      landscapePromptZh,
      landscapeExplainEn,
      landscapeExplainZh,
      culturePromptEn,
      culturePromptZh,
      cultureExplainEn,
      cultureExplainZh,
    ] = fields;
    return [
      country,
      [
        {
          prompt: [landscapePromptEn, landscapePromptZh],
          explain: [landscapeExplainEn, landscapeExplainZh],
        },
        {
          prompt: [culturePromptEn, culturePromptZh],
          explain: [cultureExplainEn, cultureExplainZh],
        },
      ],
    ] as const;
  });
  if (new Set(entries.map(([country]) => country)).size !== entries.length) {
    throw new Error("Country context question IDs must be unique.");
  }
  return Object.fromEntries(entries);
}
